language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DJANGO_SPEC=<1.12 CELERY_SPEC=<4.0
  - DJANGO_SPEC=<1.12 CELERY_SPEC=<4.1
  - DJANGO_SPEC=<1.12 CELERY_SPEC=<4.2
  - DJANGO_SPEC=<1.12 CELERY_SPEC=<4.3
  - DJANGO_SPEC= CELERY_SPEC=

install:
  - "pip install \"Django${DJANGO_SPEC}\" \"celery${CELERY_SPEC}\""
  - pip install -r requirements.txt .

services:
  - postgresql

addons:
  postgresql: "9.5"

sudo: required

before_script:
  - psql -c "create user tenant_celery with password 'qwe123'" -U postgres
  - psql -c "alter role tenant_celery createdb" -U postgres

script: "cd test_app && DJANGO_SETTINGS_MODULE=test_app.settings pytest ../tenant_schemas_celery/tests.py"
